# Default values for genesis.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: image-name
  tag: master
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""
name: sybil-ui

service:
  name: sybil-ui
  type: NodePort
  port: 80
  protocol: TCP
  targetPort: 80

ingress:
  host: sybil.based.loans
  secret: based.loans-tls
  path: /

environment: []

resources: 
  requests:
    cpu: 0
    memory: 0

nodeSelector: {}

tolerations: []

affinity: {}

secretMounts: []